- name: azure-blob-copy-action
  # You may pin to the exact commit or the version.
  # uses: ulaval/azure-blob-copy-action@a5589c66042be9a15da7cc2a28e63adc3a42af3a
  uses: ulaval/azure-blob-copy-action@v1
  with:
    # Either upload or download
    action: # default is upload
    # Azure Blob Storage connection string
    connection_string: DefaultEndpointsProtocol=https;AccountName=jmo1deployments;AccountKey=r6sl5Ag4YBbRn2Hs87knB0SbZ7HM+swGf/8ItmDDO+C4QVjZu+27OvJNpLu+GbV9PO3jBJdzIxlDHySH5TR2RA==;EndpointSuffix=core.windows.net
    # Azure Blob Storage container name
    container_name: github
    # Directory in Azure to copy from or to
    blob_directory: # optional
    # Local directory to copy from or to; this can either be an absolute path or a relative path
    local_directory: ADDS_GIT
    # YAML document that allows setting http headers on blobs when uploading to Azure.

The supported headers are: Cache-Control, Content-Type, Content-Encoding, Content-Language, Content-Disposition (case sensitive).

The yaml document must resolve to an array where each element has a <glob> and <headers> values.

If a file is matched at multiple times, the first match wins.

By default, the Content-Type is discovered using mime-db mostly using UTF-8 charset.

For example:

http_headers: |
  - glob: "**/*.js"
    headers:
      Cache-Control: public, max-age=604800, immutable
      Content-Type: application/javascript
      Content-Encoding: gzip
      Content-Language: fr-CA
      Content-Disposition: inline

  - glob: "**/*":
    headers:
      Cache-Control: public, no-cache

    http_headers: # optional
